### ISSUE TITLE
plugin not work

### ISSUE THREAD

**Issue by haKingdomsCraft** [DuooIncc/Relics#3]
please fix it and do gems plugin

**Comment by DuooIncc** [comment]
It would be nice for you to tell me whatbisnt working ir include a file of the issue.

**Comment by haKingdomsCraft** [comment]
When u click on relic is not do anything

**Comment by DuooIncc** [comment]
Its not meant to right now. It is still in development

**Comment by lcyLand** [comment]
close this properly @DuooIncc

**Comment by DuooIncc** [comment]
Happy @lcyLand
